# Generated by Django 3.2.9 on 2022-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='label',
        ),
        migrations.AddField(
            model_name='counter',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='counter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
